import streamlit as st
import pandas as pd
import plotly.express as px
import time

# ตั้งค่าหน้าเว็บ
st.set_page_config(page_title="GeoFeas AI - Energy Infrastructure Feasibility", layout="wide")

st.title("⚡ GeoFeas AI")
st.subheader("OpenAI-Powered Energy Infrastructure Feasibility & Capacity Planning")
st.write("---")

# ส่วนรับข้อมูล Input (Sidebar)
st.sidebar.header("📁 Input Parameters")
station_name = st.sidebar.text_input("Station Name", "PTT NGV Main Station Alpha")
station_type = st.sidebar.selectbox("Station Type", ["NGV Station", "EV Supercharger Hub", "Hydrogen Refueling"])
target_capacity = st.sidebar.slider("Target Daily Capacity (kg/kWh)", 1000, 10000, 5000, step=500)

# จำลองข้อมูลประวัติการทำธุรกรรม (Historical Transactions)
st.subheader("📈 Historical Transaction & Demand Analysis")
chart_data = pd.DataFrame({
    'Hour': list(range(24)),
    'Historical Demand (kg)': [120, 90, 80, 50, 70, 150, 300, 450, 400, 350, 300, 320, 380, 410, 390, 350, 420, 480, 500, 420, 300, 240, 180, 140]
})
fig = px.line(chart_data, x='Hour', y='Historical Demand (kg)', title="Daily Demand Curve Profile")
st.plotly_chart(fig, use_container_width=True)

# ปุ่มกดประมวลผลด้วย OpenAI
st.write("---")
st.subheader("🤖 Generative AI Feasibility Analysis")
if st.button("Generate Feasibility Report with OpenAI"):
    with st.spinner("OpenAI (GPT-4o) is analyzing spatial data, demand curves, and ROI metrics..."):
        time.sleep(3) # จำลองเวลาประมวลผล
        
        st.success("Analysis Complete!")
        
        # แสดงผลลัพธ์จำลอง
        col1, col2, col3 = st.columns(3)
        col1.metric("Feasibility Score", "87/100", "High Viability")
        col2.metric("Projected Payback Period", "4.2 Years", "-0.8 Years vs Avg")
        col3.metric("Recommended Daily Capacity", f"{target_capacity} kg", "Optimized")
        
        st.markdown("""
        ### **Executive Summary Report (Generated by OpenAI GPT-4o)**
        
        *   **Spatial Analysis:** Location is highly strategic. It intercepts key logistics corridors with a high volume of heavy-duty commercial fleets.
        *   **Capacity Recommendation:** Your target of **{capacity} kg** is well-optimized. The historical peak demand at 18:00 suggests adding a secondary compressor to prevent bottlenecking.
        *   **Financial Viability:** High ROI expected. Payback period is reduced due to proximity to the main gas pipeline.
        *   **Risk Mitigation:** Recommended to establish dual-sourced power backup to prevent downtime during peak grid usage hours.
        """.format(capacity=target_capacity))
